# Generated by Django 5.2 on 2025-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('visto', models.BooleanField(default=False)),
                ('nota', models.IntegerField(choices=[(0, '0 - Péssimo'), (1, '1 - Muito Ruim'), (2, '2 - Ruim'), (3, '3 - Ok'), (4, '4 - Bom'), (5, '5 - Fantástico')])),
                ('review', models.TextField(blank=True, null=True)),
                ('filme_id', models.IntegerField()),
            ],
        ),
    ]
